/*
 * ConfigDialog.java
 *
 * Created on September 19, 2004, 2:40 PM
 */

package DocCharConvert;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import java.io.File;
/**
 *
 * @author  keith
 */
public class ConfigDialog extends javax.swing.JDialog
{
    
    /** Creates new form ConfigDialog */
    public ConfigDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        ooPath.setText(Config.getCurrent().getOOPath());
        ooOptionsField.setText(Config.getCurrent().getOOOptions());
        unoField.setText(Config.getCurrent().getOOUNO());
        try 
        {
            converterPath.setText(Config.getCurrent().getBasePath().getCanonicalPath());
        }
        catch (java.io.IOException e)
        {
            System.out.println(e.getLocalizedMessage());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ooPanel = new javax.swing.JPanel();
        ooPathPanel = new javax.swing.JPanel();
        ooPathLabel = new javax.swing.JLabel();
        ooPath = new javax.swing.JTextField();
        ooPathButton = new javax.swing.JButton();
        ooOptionsPanel = new javax.swing.JPanel();
        optionsLabel = new javax.swing.JLabel();
        ooOptionsField = new javax.swing.JTextField();
        unoAddressPanel = new javax.swing.JPanel();
        unoLabel = new javax.swing.JLabel();
        unoField = new javax.swing.JTextField();
        converterPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        convLabel = new javax.swing.JLabel();
        converterPath = new javax.swing.JTextField();
        convPathButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        ooPanel.setLayout(new javax.swing.BoxLayout(ooPanel, javax.swing.BoxLayout.Y_AXIS));

        ooPanel.setBorder(new javax.swing.border.TitledBorder("OpenOffice Config"));
        ooPathPanel.setLayout(new javax.swing.BoxLayout(ooPathPanel, javax.swing.BoxLayout.X_AXIS));

        ooPathPanel.setAlignmentX(0.0F);
        ooPathLabel.setText("Path: ");
        ooPathPanel.add(ooPathLabel);

        ooPath.setText("ooffice");
        ooPath.setToolTipText("Path to OO Executable, or just the executable name if it is already in your PATH.");
        ooPath.setMaximumSize(new java.awt.Dimension(200, 20));
        ooPath.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ooPathActionPerformed(evt);
            }
        });

        ooPathPanel.add(ooPath);

        ooPathButton.setText("Browse...");
        ooPathButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ooPathButtonActionPerformed(evt);
            }
        });

        ooPathPanel.add(ooPathButton);

        ooPanel.add(ooPathPanel);

        ooOptionsPanel.setLayout(new javax.swing.BoxLayout(ooOptionsPanel, javax.swing.BoxLayout.X_AXIS));

        ooOptionsPanel.setAlignmentX(0.0F);
        optionsLabel.setText("Options: ");
        ooOptionsPanel.add(optionsLabel);

        ooOptionsField.setText(" -headless -accept=socket,hostname=localhost,port=8100;urp;");
        ooOptionsField.setToolTipText("Host and Port must be correct. Do not change these unless you understand what you are doing.");
        ooOptionsField.setMaximumSize(new java.awt.Dimension(400, 20));
        ooOptionsPanel.add(ooOptionsField);

        ooPanel.add(ooOptionsPanel);

        unoAddressPanel.setLayout(new javax.swing.BoxLayout(unoAddressPanel, javax.swing.BoxLayout.X_AXIS));

        unoAddressPanel.setAlignmentX(0.0F);
        unoLabel.setText("UNO Address: ");
        unoAddressPanel.add(unoLabel);

        unoField.setText("uno:socket,host=localhost,port=8100;urp;StarOffice.ServiceManager");
        unoField.setToolTipText("Host and Port must be correct. Do not change these unless you understand what you are doing.");
        unoField.setMaximumSize(new java.awt.Dimension(400, 20));
        unoAddressPanel.add(unoField);

        ooPanel.add(unoAddressPanel);

        jTabbedPane1.addTab("OpenOffice", ooPanel);

        converterPanel.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel8.setAlignmentX(0.0F);
        convLabel.setText("Converter Path: ");
        jPanel8.add(convLabel, java.awt.BorderLayout.WEST);

        converterPath.setToolTipText("Path to OO Executable, or just the executable name if it is already in your PATH.");
        converterPath.setMaximumSize(new java.awt.Dimension(200, 15));
        converterPath.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                converterPathActionPerformed(evt);
            }
        });

        jPanel8.add(converterPath, java.awt.BorderLayout.CENTER);

        convPathButton.setText("Browse...");
        convPathButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                convPathButtonActionPerformed(evt);
            }
        });

        jPanel8.add(convPathButton, java.awt.BorderLayout.EAST);

        converterPanel.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        converterPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Converters", converterPanel);

        jPanel1.add(jTabbedPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okButtonActionPerformed(evt);
            }
        });

        jPanel2.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel2.add(cancelButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void convPathButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_convPathButtonActionPerformed
    {//GEN-HEADEREND:event_convPathButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileFilter(new FileFilter() {
            public boolean accept(java.io.File file)
            {
                if (file.isDirectory()) return true;
                if (file.getName().toLowerCase().endsWith(".dccx")) 
                    return true;
                return false;
            }
            public String getDescription() { return "DocCharConverter files"; }
        });
        if (chooser.showOpenDialog(this)  == 
            JFileChooser.APPROVE_OPTION)
        {
            try
            {
                File chosen = chooser.getSelectedFile();
                if (chosen.getName().toLowerCase().endsWith(".dccx"))
                    converterPath.setText(chosen.getParentFile().getCanonicalPath());
                else if (chosen.isDirectory())
                    converterPath.setText(chosen.getCanonicalPath());
            }
            catch (java.io.IOException e)
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_convPathButtonActionPerformed

    private void converterPathActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_converterPathActionPerformed
    {//GEN-HEADEREND:event_converterPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_converterPathActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void ooPathButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ooPathButtonActionPerformed
    {//GEN-HEADEREND:event_ooPathButtonActionPerformed
        // Add your handling code here:
               
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileFilter(new FileFilter() {
            public boolean accept(java.io.File file)
            {
                if (file.isDirectory()) return true;
                if (file.getName().toLowerCase().endsWith(".exe")) 
                    return true;
                if (file.getName().toLowerCase().startsWith("ooffice"))
                    return true;
                if (file.getName().toLowerCase().startsWith("soffice"))
                    return true;
                return false;
            }
            public String getDescription() { return "Text files"; }
        });
        if (chooser.showOpenDialog(this)  == 
            JFileChooser.APPROVE_OPTION)
        {
            try
            {
                ooPath.setText(chooser.getSelectedFile().getCanonicalPath());
            }
            catch (java.io.IOException e)
            {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_ooPathButtonActionPerformed

    private void ooPathActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ooPathActionPerformed
    {//GEN-HEADEREND:event_ooPathActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_ooPathActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
        Config.getCurrent().setOOPath(ooPath.getText());
        Config.getCurrent().setOOOptions(ooOptionsField.getText());
        Config.getCurrent().setOOUNO(unoField.getText());
        Config.getCurrent().setBasePath(new File(converterPath.getText()));
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
    {
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        new ConfigDialog(new javax.swing.JFrame(), true).setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel convLabel;
    private javax.swing.JButton convPathButton;
    private javax.swing.JPanel converterPanel;
    private javax.swing.JTextField converterPath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField ooOptionsField;
    private javax.swing.JPanel ooOptionsPanel;
    private javax.swing.JPanel ooPanel;
    private javax.swing.JTextField ooPath;
    private javax.swing.JButton ooPathButton;
    private javax.swing.JLabel ooPathLabel;
    private javax.swing.JPanel ooPathPanel;
    private javax.swing.JLabel optionsLabel;
    private javax.swing.JPanel unoAddressPanel;
    private javax.swing.JTextField unoField;
    private javax.swing.JLabel unoLabel;
    // End of variables declaration//GEN-END:variables
    
}
